### ISSUE TITLE
Forbidden - after logging in with admin/admin

### ISSUE THREAD

**Issue by mbonaci** [ChrisZieba/LogicPull#16]
The result of logging in is this:

```
Error: Forbidden
    at Object.exports.error (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/utils.js:62:13)
    at Object.module.exports [as handle] (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41)
    at next (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/middleware/session.js:301:7)
    at next (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:49:5)
    at next (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at module.exports (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9)
    at IncomingMessage.module.exports (/srv/www/LogicPull/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
```

I'm trying to make this work on Ubuntu 14.04.1, using Node v0.8.8 (trying to make the environment the same as yours).
I was following the server-installation tutorial and then local-installation and the same error happens in both installments.
Nginx and Varnish are working fine, AFAICS.

Thanks

**Comment by ChrisZieba** [comment]
I believe the cookie domain being set to "localhost" is the problem here. Try adding a domain to your hosts file and using that instead.
